import SEO from "@components/seo";
import Wrapper from "@layout/wrapper";
import Header from "@layout/header/header-01";
import Footer from "@layout/footer/footer-01";
import Breadcrumb from "@components/breadcrumb";
import ExploreProductArea from "@containers/explore-product/layout-12";

export async function getStaticProps() {
    return { props: { className: "template-color-1" } };
}

const whereToBuy = [
    {
        name: "CBS Products (KT)",
        roadOne: "Pillings Road",
        roadTwo: "Oakham",
        county: "Rutland",
        postcode: "LE15 6QF",
        country: "UK",
        contact: "",
        mobile: "",
        fax: "",
        tel: "+44 (0) 1572 723 665",
        email: "sales@cbsproducts.com",
        website: "/",
        img: "cbslogo.jpeg",
    },
    {
        name: "Amadys",
        roadOne: "Amadys Belgium Headquarter",
        roadTwo: "Sint-Pietersvliet 7",
        county: "",
        postcode: "2000 Antwerpen",
        country: "Belgium",
        tel: "+32 3 202 16 50",
        mobile: "",
        fax: "",
        contact: "",
        email: "info@amadys.com",
        website: "https://www.amadys.com/en/",
        img: "amadys.png",
    },
    {
        name: "Telenco UK",
        roadOne: "Hillmead Enterprise Park",
        roadTwo: "Unit 3 Westerngate, Langley Rd",
        county: "Swindon",
        postcode: "SN5 5WN",
        country: "UK",
        tel: "01793 848123",
        mobile: "",
        fax: "",
        contact: "",
        email: "sales.uk@telenco.com",
        website: "https://www.telenco.uk/",
        img: "telencologo.jpeg",
    },
    {
        name: "Gigabit Utility Supplies, Unit 3",
        roadOne: "Crags Industrial Park",
        roadTwo: "Morven Street",
        county: "Creswell",
        postcode: "S80 4AJ",
        country: "UK",
        contact: "James Shaw",
        mobile: "07939 296615",
        tel: "07939 296615",
        fax: "",
        email: "sales@gigabitutilitysupplies.co.uk",
        website: "https://gigabitutilitysupplies.co.uk/contact-us/",
        img: "gus.jpg",
    },
    {
        name: "PMD Business Finance",
        roadOne: "2 Howarth Court",
        roadTwo: "Gateway Crescent",
        county: "Oldham",
        postcode: "OL9 9XB",
        country: "UK",
        tel: "0161 627 7486",
        mobile: "07702 551383",
        fax: "",
        contact: "Rob Greenhalgh",
        email: "robg@pmdbusinessfinance.co.uk",
        website: "https://www.pmdbusinessfinance.co.uk",
        img: "pmd.png",
    },
    {
        name: "UK HIRE PARTNER",
        roadOne: "",
        roadTwo: "",
        county: "",
        postcode: "",
        country: "",
        tel: "",
        fax: "",
        mobile: "07742404707",
        contact: "Dave Randall",
        email: "dave.randall@wolseley.co.uk",
        website: "https://www.fusion-utilities.co.uk",
        img: "fusionutilitieslogo.png",
    },
    {
        name: "CBI Electric Telecom Cables (Pty) Ltd",
        roadOne: "3 Marthinus Ras Street",
        roadTwo: "Industrial Sites",
        county: "Brits",
        postcode: "North West Province",
        country: "South Africa",
        tel: "+27 12 381 1400",
        mobile: "+27 83 663 3368",
        fax: "+27 12 381 1564",
        contact: "Wynand Frost",
        email: "wfrost@cbitele.com",
        website: "https://www.cbitele.com",
        img: "cbielectricallogo.jpeg",
    },
    {
        name: "D.J.Global Creation Co. Ltd",
        roadOne: "137/79-80 Moo 1 Nanthanagarden Soi 12",
        roadTwo: "Pathumthani-Rangsit Road",
        county: "Banklang Muang Pathumthani",
        postcode: "Pathumthani 12000",
        country: "Thailand",
        tel: "+66 (0) 2157 2588",
        mobile: "+66 (0) 81 811 6495",
        fax: "+66 (0) 2157 2589",
        contact: "Jeffery Jia",
        email: "info@djglobalcreation.com",
        website: "https://www.djglobalcreation.com",
        img: "djgloballogo.jpeg",
    },
    {
        name: "Paviot Equipment",
        roadOne: "16 Rue Des Taillées",
        roadTwo: "79180 Chauray",
        county: "05 49 79 07 05",
        roadThree: "98 Rue Louis Ampère",
        roadFour: "93330 Neuilly-Sur-Marne",
        countyTwo: "01 43 00 43 00",
        postcodeTwo: "",
        country: "France",
        tel: "",
        mobile: "",
        fax: "",
        contact: "",
        email: "contact@paviotequipement.fr",
        website: "https://www.paviotequipement.fr",
        img: "paviotlogo.jpeg",
    },
    {
        name: "Exceed Solutions P.C.",
        roadOne: "76 Ymittou Street",
        roadTwo: "",
        county: "Athens",
        postcode: "GR-11634",
        country: "Greece",
        tel: "0030 6944 741 005",
        mobile: "",
        fax: "",
        contact: "Vladimir Peteropoulos",
        email: "info@exceedsolutions.gr",
        website: "https://www.exceedsolutions.gr",
        img: "exceed_logo.jpeg",
    },
    {
        name: "GA Telecomunicazioni",
        roadOne: "Via dante Alighieri, 6",
        roadTwo: "",
        county: "",
        postcode: "20050 – Sovico (MI)",
        country: "Italy",
        tel: "+390392011285",
        mobile: "",
        fax: "+390392016636",
        contact: "",
        email: "info@gatelecomunicazioni.com",
        website: "https://www.gatelecomunicazioni.com",
        img: "GA_tele_logo.jpeg",
    },
    {
        name: "Fibrain Sp.z o.o.",
        roadOne: "Zaczernie 190F",
        roadTwo: "",
        county: "",
        postcode: "36-062 Zaczernie",
        country: "Poland",
        tel: "+48 17 86 60 800",
        mobile: "",
        fax: "+48 17 86 60 810",
        contact: "",
        email: "Info@fibrain.com",
        website: "https://www.fibrain.com",
        img: "fibrainlogo.png",
    },
    {
        name: "Teledatanet srl",
        roadOne: "Blvd 21 Decembrie 1989",
        roadTwo: "Nr. 140-155",
        county: "Cluj-Napoca",
        postcode: "RO-400604",
        country: "Romania",
        tel: "+40 264 447 999",
        mobile: "",
        fax: "+40 264 447 988",
        contact: "Dinu M. Dragomir",
        email: "dinu.dragomir@teledatanet.com",
        website: "https://www.teledatanet.com",
        img: "teledatanet-logo.png",
    },
    {
        name: "Argano Group",
        roadOne: "Calle Serranía de Ronda, 15",
        roadTwo: "28691 Villanueva de la Cañada",
        county: "Madrid",
        postcode: "",
        country: "Spain",
        tel: "+34 918 283 530",
        mobile: "",
        fax: "",
        contact: "Javier Mudarra",
        email: "comercial@arganogroup.com",
        website: "https://www.arganogroup.com",
        img: "argano-logo.jpeg",
    },
    {
        name: "MFS-Tech",
        roadOne: "Hungerbuhlstrasse 10",
        roadTwo: "",
        county: "",
        postcode: "CH-8500 Frauenfeld",
        country: "Switzerland",
        tel: "+41 52 741 41 00",
        mobile: "",
        fax: "+41 52 741 18 88",
        contact: "Dinu M. Dragomir",
        email: "info@mfs-tech.ch",
        website: "https://www.mfs-tech.ch",
        img: "MFSTECHlogo.jpeg",
    },
    {
        name: "Helsingin Laatulaite Oy",
        roadOne: "Päivöläntie 39",
        roadTwo: "",
        county: "",
        postcode: "00730 Helsinki",
        country: "Finland",
        tel: "+358 9 346 2320",
        mobile: "+358 400 460 413",
        fax: "",
        contact: "Susanna Viitala",
        email: "myynti@helsinginlaatulaite.fi",
        website: "https://www.helsinginlaatulaite.fi",
        img: "Helsinginlogo.png",
    },
    {
        name: "General Machine Products (KT), LLC (GMP)",
        roadOne: "3111 Old Lincoln Hwy",
        roadTwo: "Trevose",
        county: "",
        postcode: "Pa 19053-4996",
        country: "USA",
        tel: "+1 215 357 5500",
        mobile: "",
        fax: "+1 215 357 6216",
        contact: "Ted Clemens, Director Sales",
        email: "info@gmptools.com",
        website: "https://www.gmptools.com",
        img: "GMP-Tools-logo.jpeg",
    },
    {
        name: "Midland Site Supplies",
        roadOne: "Old Bacon Factory",
        roadTwo: "Castleholding",
        county: "Rosecrea",
        postcode: "Eire",
        country: "UK",
        contact: "Brian McCartney",
        mobile: "",
        fax: "",
        tel: "+ 353 87 358 7208",
        email: "brian@midlandsitesupplies.ie",
        website: "https://www.midlandsitesupplies.ie",
        img: "msslogo.jpeg",
    },
    {
        name: "Testronix Inc.",
        roadOne: "Unit 415 VGP Center",
        roadTwo: "(Formerly Manila Bank Building)",
        county: "6772 Ayala Avenue",
        postcode: "Makati City 1226",
        country: "Philippines",
        contact: "Ian Urmeneta",
        mobile: "",
        fax: "",
        tel: "+63 917 847 8039",
        email: "ian_urmeneta@testronix.com.ph",
        website: "http://www.testronix.com.ph",
        img: "testronixlogo.jpeg",
    },
];

const Product = () => (
    <Wrapper>
        <SEO pageTitle="Where to Buy" />
        <Header />
        <main id="main-content">
            <Breadcrumb pageTitle="Our Products" currentPage="Our Products" />
            <ExploreProductArea
                data={{
                    products: whereToBuy,
                }}
            />
        </main>
        <Footer />
    </Wrapper>
);

export default Product;
